import { uid, today } from '../utils/helpers.js';
import { T } from '../theme/tokens.js';

// ===================== INITIAL DATA =====================
const initData = () => ({
  areas:[
    {id:uid(),name:'Salud',color:T.areaColors[1],icon:'💪'},
    {id:uid(),name:'Trabajo',color:T.areaColors[0],icon:'💼'},
    {id:uid(),name:'Finanzas',color:T.areaColors[2],icon:'💰'},
    {id:uid(),name:'Hogar',color:T.areaColors[3],icon:'🏠'},
    {id:uid(),name:'Desarrollo Personal',color:T.areaColors[4],icon:'🧠'},
    {id:uid(),name:'Relaciones',color:T.areaColors[5],icon:'👥'},
    {id:uid(),name:'Side Projects',color:T.areaColors[6],icon:'🚀'},
  ],
  objectives:[{id:uid(),title:'Correr una maratón',areaId:'',deadline:'2026-12-31',status:'active'}],
  projects:[],tasks:[],
  notes:[{id:uid(),title:'Cómo funciona el Segundo Cerebro',content:'El Segundo Cerebro es un sistema para externalizar nuestra memoria y liberar carga cognitiva. Basado en el método de Tiago Forte: Áreas → Objetivos → Proyectos → Tareas.',tags:['productividad','sistema'],areaId:'',createdAt:today()}],
  inbox:[{id:uid(),content:'Revisar el sistema de Segundo Cerebro',createdAt:today(),processed:false}],
  habits:[
    {id:uid(),name:'Meditar 10 min',frequency:'daily',completions:[]},
    {id:uid(),name:'Leer 30 min',frequency:'daily',completions:[]},
    {id:uid(),name:'Ejercicio',frequency:'daily',completions:[]},
  ],
  budget:[],
  transactions:[],
  healthMetrics:[],
  healthGoals:{peso:75,sueño:8,pasos:10000,agua:2,entrenosSem:4},
  medications:[],
  workouts:[],
  maintenances:[],
  homeDocs:[],
  homeContacts:[],
  learnings:[],
  retros:[],
  ideas:[],
  people:[],
  followUps:[],
  interactions:[],
  sideProjects:[],
  spTasks:[],
  milestones:[],
  spTimeLogs:[],
  journal:[],
  books:[],
  shopping:[{id:uid(),name:'Leche',qty:2,unit:'L',category:'Lácteos',done:false,createdAt:today()},{id:uid(),name:'Pan integral',qty:1,unit:'pza',category:'Panadería',done:false,createdAt:today()}],
  education:[],
  carMaintenances:[],
  carExpenses:[],
  carDocs:[],
  carReminders:[],
  carInfo:{brand:'',model:'',year:'',plate:'',km:'',fuelType:'gasolina',fuelType1:'',fuelType2:''},
  vehicles:[],
  activeVehicleId:null,
  // Tanda 2 — Nutrición y Sueño
  recipes:[],
  weekMenus:{},
  sleepLog:[],
  dreamJournal:[],
  // Tanda 1 — nuevos módulos
  entertainment:[],
  pets:[],
  petVaccines:[],
  petVetVisits:[],
  trips:[],
  tripStops:[],
  tripExpenses:[],
  tripChecklist:{},
});

export { initData };
