import { uid } from '../utils/helpers.js';
import { T } from '../theme/tokens.js';

// ===================== INITIAL DATA =====================
const initData = () => ({
  areas:[
    {id:uid(),name:'Salud',color:T.areaColors[1],icon:'💪'},
    {id:uid(),name:'Trabajo',color:T.areaColors[0],icon:'💼'},
    {id:uid(),name:'Finanzas',color:T.areaColors[2],icon:'💰'},
    {id:uid(),name:'Hogar',color:T.areaColors[3],icon:'🏠'},
    {id:uid(),name:'Desarrollo Personal',color:T.areaColors[4],icon:'🧠'},
    {id:uid(),name:'Relaciones',color:T.areaColors[5],icon:'👥'},
    {id:uid(),name:'Side Projects',color:T.areaColors[6],icon:'🚀'},
  ],
  objectives:[],
  projects:[],tasks:[],
  notes:[],
  inbox:[],
  habits:[],
  budget:[],
  transactions:[],
  healthMetrics:[],
  healthGoals:{peso:0,sueño:0,pasos:0,agua:0,entrenosSem:0},
  medications:[],
  workouts:[],
  maintenances:[],
  homeDocs:[],
  homeContacts:[],
  learnings:[],
  retros:[],
  ideas:[],
  people:[],
  followUps:[],
  interactions:[],
  sideProjects:[],
  spTasks:[],
  milestones:[],
  spTimeLogs:[],
  journal:[],
  books:[],
  shopping:[],
  education:[],
  carMaintenances:[],
  carExpenses:[],
  carDocs:[],
  carReminders:[],
  carInfo:{brand:'',model:'',year:'',plate:'',km:'',fuelType:'gasolina',fuelType1:'',fuelType2:''},
  vehicles:[],
  activeVehicleId:null,
  entertainment:[],
  pets:[],
  petVaccines:[],
  petVetVisits:[],
  trips:[],
  tripStops:[],
  tripExpenses:[],
  tripChecklist:{},
  recipes:[],
  weekMenus:{},
  sleepLog:[],
  dreamJournal:[],
  moments:[],
  habitChallenges:[],
  medicalVisits:[],
  medicalDocs:[],
  farmaciaItems:[],
  reminders:[],
});

export { initData };
